### ISSUE TITLE
Why doesn't this point have data?

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/hsiaa#69]
https://snap.uaf.edu/tools/sea-ice-atlas/report/63.731/5.4072

Seems like it should be within the data footprint!

**Comment by BobTorgerson** [comment]
This data is within the data footprint, but the HSIA code specifically doesn't allow for areas with zero sea ice concentration, so this is working as expected. 

Here is the data from the API for this location: https://earthmaps.io/seaice/point/63.731/5.4072/
